<h3>NumPy Hands-On Practice</h3>

<h4>HANDS-ON 1: Meet Your First NumPy Arrays</h4>

<p><b>Objective</b><br>
By the end of this activity, you should be able to:</p>
<ul>
  <li>Import NumPy</li>
  <li>Create a NumPy array from a Python list</li>
  <li>Identify a 1D array</li>
  <li>Inspect the array's data type</li>
  <li>Create a 2D array</li>
  <li>Begin thinking in terms of dimensions</li>
</ul>

<br>

<p><b>Scenario</b><br>
Imagine you are working with a small weather-monitoring team.<br>
The team recorded the temperature in °C for three days:</p>
<pre><code>temperatures = [27.5, 29.0, 28.5]</code></pre>
<p>Your job is to convert this information into a NumPy array and inspect what you have.</p>

<br>

<p><b>Task 1 — Import NumPy</b><br>
Write the code required to import NumPy using the conventional alias:</p>
<pre><code>import numpy as np</code></pre>

<p>Run the cell.</p>

<br>

<p><b>Question</b><br>
If the cell runs without an error, what does that tell you?<br>
Write your answer as a comment in your notebook.</p>

In [5]:
import numpy as np

# The cells runs without an error and this tells me that numpy has been successfully installes
# It has now been successfully imported with an alias np

<p><b>Task 2 — Create Your Array</b><br>
Convert the <code>temperatures</code> list into a NumPy array.</p>

<p><b>Your output should represent:</b></p>
<pre><code>[27.5 29.  28.5]</code></pre>

<p><b>Your task:</b><br>
Write the Python code yourself.</p>

In [7]:
temperatures = [27.5, 29.0, 28.5]
temperature_array = np.array(temperatures)

print(temperature_array)

[27.5 29.  28.5]


<p><b>Task 3 — Inspect the Data Type</b><br>
Use the appropriate NumPy attribute to find the data type of your array.</p>

<p><b>Think carefully:</b><br>
Which concept did we learn that describes the data type of a NumPy array?</p>

In [9]:
print(type(temperature_array))

<class 'numpy.ndarray'>


<p><b>Task 4 — Create a 2D Array</b><br>
Now imagine three weather stations recorded temperatures over two days:</p>

<pre><code>weather_data = [
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]</code></pre>

<p>Convert this into a NumPy array.</p>

<br>

<p><b>Challenge</b><br>
Before running your code, predict:</p>
<ul>
  <li>Is this a 1D or 2D array?</li>
  <li>Is it a vector or matrix?</li>
  <li>How many rows does it have?</li>
  <li>How many values are in each row?</li>
</ul>
<p>Then run your code and compare your prediction with the result.</p>

<br>

<p><b>Buddy Hint</b><br>
Look at the structure carefully.<br>
A list inside another list should make you think about dimensions.</p>

In [14]:
weather_data = [
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]
weather_data_array = np.array(weather_data)
print(weather_data_array)
# I got exactly what I predicted
# It is a 2D array
# Also known as a matrix
# It has two rows and three columns

[[27.5 28.  29.5]
 [28.  29.  30. ]]


<h4>HANDS-ON 2: Python Lists vs NumPy Arrays</h4>

<p><b>Objective</b><br>
This activity is designed to make one important difference impossible to forget:<br>
Python lists and NumPy arrays do not behave the same way when you perform numerical operations.</p>

<br>

<p><b>Scenario</b><br>
You are working with a small retail business.<br>
The business recorded the number of products sold by two sales representatives over three days:</p>

<pre><code>sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]</code></pre>

<p>The manager wants to know the combined sales for each day.<br>
The expected result is:</p>
<pre><code>[15, 25, 35]</code></pre>

<p><b>Task 1 — Try It With Python Lists</b><br>
Create:</p>

<pre><code>sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]</code></pre>

<p>Now try:</p>
<pre><code>sales_timothy + sales_brenda</code></pre>

<p><b>Stop!</b><br>
Before moving forward, look carefully at the result.<br>
Answer these questions:</p>

<ol>
  <li>Did Python produce <code>[15, 25, 35]</code>?</li>
  <li>What did Python actually do?</li>
  <li>Why do you think that happened?</li>
</ol>

<p>Write your answers as comments in your notebook.</p>

In [15]:
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

combined_sales = sales_timothy + sales_brenda
print(combined_sales)

# It did not produce the intended answer
# python actually did list concatenation
# it places the values of the list side by side in a new list

[10, 15, 20, 5, 10, 15]


<p><b>Task 2 — Convert Them to NumPy Arrays</b><br>
Convert both lists into NumPy arrays.</p>

<p>For example, you should create something conceptually like:</p>
<pre><code>sales_timothy → NumPy array
sales_brenda → NumPy array</code></pre>

<p>Then add the two arrays.</p>

In [16]:
timothy_sales_array = np.array(sales_timothy)
brenda_sales_array = np.array(sales_brenda)

combined_sales_array = timothy_sales_array + brenda_sales_array
print(combined_sales_array)

[15 25 35]


<p><b>Task 3 — Compare the Results</b><br>
Create a small comparison in your notebook:</p>

<table>
  <thead>
    <tr>
      <th>Approach</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Python lists</td>
      <td>?</td>
    </tr>
    <tr>
      <td>NumPy arrays</td>
      <td>?</td>
    </tr>
  </tbody>
</table>

<br>

<p><b>Then answer:</b><br>
Why is NumPy useful here?</p>

<p><b>Don't answer:</b><br>
<i>"Because NumPy is faster."</i><br>
That answer is incomplete.<br>
Explain what NumPy allows you to do with the data.</p>

<br>

<p><b>Challenge</b><br>
Create two new arrays:</p>
<ul>
  <li><code>online_sales</code></li>
  <li><code>store_sales</code></li>
</ul>

<p>Use five days of imaginary sales data.<br>
For example, you might have:</p>
<ul>
  <li>Monday</li>
  <li>Tuesday</li>
  <li>Wednesday</li>
  <li>Thursday</li>
  <li>Friday</li>
</ul>

<p>Calculate the combined sales for each day.<br>
Then create a second operation that calculates the difference between online and store sales.</p>

<br>

<p><b>Buddy Hint</b><br>
NumPy arrays allow arithmetic operations to be performed element by element.<br>
Think:</p>
<ul>
  <li>Day 1 → Day 1</li>
  <li>Day 2 → Day 2</li>
  <li>Day 3 → Day 3</li>
</ul>

In [18]:
# python list answer → [10, 15, 20, 5, 10, 15]
# numpy array answer → [15 25 35]

# Numpy is useful here because it makes element-based addition seamlessly done

online_sales = np.array([10, 15, 20, 10, 15])
store_data = np.array([10, 20, 5, 10, 5])

combined_sales_data = online_sales + store_data
print(combined_sales_data)

[20 35 25 20 20]


<h4>HANDS-ON 3: MINI PROJECT — Weather Data Quick Analysis</h4>

<p><b>PSG Mini Project</b></p>

<p><b>Project Title:</b><br>
Weather Temperature Analysis with NumPy</p>

<p><b>Difficulty:</b> Beginner → Intermediate</p>

<p><b>Industry Area:</b><br>
Data Analytics / Environmental Monitoring</p>

<br>

<p><b>Project Scenario</b><br>
Study Buddy, imagine you have been given a small dataset from a weather-monitoring station.<br>
The station recorded daily temperatures for one week.<br>
Your job is to use NumPy to turn the raw numerical data into something that can be analyzed.</p>

<p>Here is your dataset:</p>
<pre><code>temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]</code></pre>

<p>You have been asked to perform some basic numerical analysis.</p>

<p><b>Part 1 — Create the Dataset</b></p>

<p>Import NumPy:</p>
<pre><code>import numpy as np</code></pre>

<p>Create the Python list:</p>
<pre><code>temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]</code></pre>

<p>Convert the list into a NumPy array.</p>

<br>

<p><b>Task</b><br>
Display your NumPy array.</p>

In [19]:
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]

temperatures_array = np.array(temperatures)
print(temperatures_array)

[27.5 29.  30.5 28.  31.  32.5 30. ]


<p><b>Part 2 — Understand Your Array</b></p>

<p>Answer the following:</p>

<p><b>Question 1</b><br>
Is your temperature array 1D or 2D?</p>

<p><b>Question 2</b><br>
Would you describe it as a vector or matrix?</p>

<p><b>Question 3</b><br>
What is its data type?</p>

<p><b>Question 4</b><br>
How many temperature observations are present?</p>

<br>

<p><b>Instruction:</b><br>
Do not simply write the answers.<br>
Use Python/NumPy where appropriate to investigate your answers.</p>

In [21]:
# 1. The temperatures_array variable I created is a 1D array
# 2. It can be described as a vector
# 3. Its data type is ndarray
# 4. There are seven temperature observations

print(type(temperatures_array))
print(len(temperatures_array))

<class 'numpy.ndarray'>
7


<p><b>Part 3 — Perform Numerical Operations</b></p>

<p>The weather team wants to compare temperatures.<br>
Create another NumPy array representing the target temperature for each day:</p>

<pre><code>target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]</code></pre>

<p>Convert it to a NumPy array.</p>

<p>Now calculate:</p>

<br>

<p><b>Task A — Temperature Difference</b><br>
Calculate the difference between the recorded temperature and the target temperature.</p>

<p>Conceptually:</p>
<pre><code>Recorded temperature - Target temperature</code></pre>

<br>

<p><b>Task B — Temperature Increase</b><br>
The monitoring team wants to simulate what the readings would look like if every temperature increased by 2°C.<br>
Create the resulting array.</p>

<p><b>Think about this carefully:</b><br>
Do you need a <code>for</code> loop to add 2 to every NumPy array element?<br>
Try to solve it using NumPy.</p>

In [30]:
target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]
target_temperature = np.array(target)

recorded_temperature = temperatures_array
temperature_difference = recorded_temperature - target_temperature
print(temperature_difference)

# If every record was increased by 2°C.
increased_temperature = recorded_temperature + 2

print(increased_temperature)

# I do not need a for loop to answer it

[-0.5  1.   1.5  0.   1.   2.5  1. ]
[29.5 31.  32.5 30.  33.  34.5 32. ]


<p><b>Part 4 — Think Like an Analyst</b></p>

<p>Now pause.<br>
Don't write code immediately.<br>
Look at the data and answer:</p>

<br>

<p><b>Business Question 1</b><br>
Which day appears to have the highest recorded temperature?</p>

<p><b>Business Question 2</b><br>
On which days was the recorded temperature above the target?</p>

<p><b>Business Question 3</b><br>
What does the temperature difference tell the weather-monitoring team?</p>

<p><b>Business Question 4</b><br>
Why would using a NumPy array be more convenient than keeping the temperatures only as a Python list for these numerical operations?</p>

<br>

<p><b>Instruction:</b><br>
Write your answers in Markdown cells.</p>

In [ ]:
# 1. friday appears to have the highest recorded temperature of 32.5
# PS: I assummed that the days reads from sunday to saturday
# 2. On Sunday, Monday, Tuesday, Thursday, Friday and Saturday, the recorded temperatures were above target temperature
# 3. Temperature difference tells the weather-monitoring team on what days the target temperatures were met, exceeded or not met
# 4. Numpy would be more convienent because it carries out arithmetic operations without extra logic and does it efficiently

<h4>MINI PROJECT CHALLENGE</h4>

<p><b>Coach Timothy is going to make this one slightly harder.</b></p>

<p>Imagine the weather station has three locations:</p>

<pre><code>lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]</code></pre>

<p>Your task is to create NumPy arrays for all three locations.</p>

<p><b>Then answer:</b></p>

<br>

<p><b>Challenge 1</b><br>
Which location recorded the highest temperature on each day?</p>

<p><b>Challenge 2</b><br>
Create a calculation that increases every recorded temperature by 1°C.</p>

<p><b>Challenge 3</b><br>
Create a calculation that compares Lagos temperatures with Abuja temperatures.</p>

<p><b>Challenge 4</b><br>
Explain why NumPy becomes increasingly useful as the amount of numerical data grows.</p>

In [40]:
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

lagos_array = np.array(lagos)
abuja_array = np.array(abuja)
ibadan_array = np.array(ibadan)

# 1. Location with highest temperature each day
max_temperature = np.maximum(np.maximum(lagos_array, abuja_array), ibadan_array)

highest_per_day = np.where(max_temperature == lagos_array, 'Lagos',
                  np.where(max_temperature == abuja_array, 'Abuja', 'Ibadan'))

print(highest_per_day)

# 2. Increasing every recorded temperature by 1
increased_lagos_array = lagos_array + 1
increased_abuja_array = abuja_array + 1
increased_ibadan_array = ibadan_array + 1

print(increased_lagos_array)
print(increased_abuja_array)
print(increased_ibadan_array)

# 3. Compare lagos and abuja tempertures
temperature_difference = lagos_array - abuja_array
print(temperature_difference)

# 4. Numpy becomes increasingly useful as the data volume increased because as the volume increases,
# python list takes a longer time to process numerical data than numpy

['Lagos' 'Lagos' 'Lagos' 'Abuja' 'Abuja']
[28.5 30.  31.5 29.  32. ]
[26.  29.  30.5 31.  33. ]
[27.5 29.5 30.  28.5 31.5]
[ 2.5  1.   1.  -2.  -1. ]


<h3>YOUR MINI PROJECT REPORT</h3>

<p>Your Jupyter Notebook should contain these sections:</p>

<ol>
  <li>Project Title</li>
  <li>Project Introduction</li>
  <li>Import NumPy</li>
  <li>Dataset</li>
  <li>Convert Data to NumPy Arrays</li>
  <li>Array Inspection</li>
  <li>Numerical Operations</li>
  <li>Lagos vs Abuja Comparison</li>
  <li>Findings</li>
  <li>Conclusion</li>
</ol>

<br>

<p><b>Instructions for the Report:</b></p>
<ul>
  <li><b>Findings Section:</b> Write at least 3 observations from your analysis. For example: <i>"The temperature data shows..."</i></li>
  <li><b>Contextual Narrative:</b> Don't just dump Python outputs into the notebook. Explain what the numbers mean in real-world agricultural or operational terms.</li>
</ul>

Project Title: Quick Weather Data Analysis

<!-- Project Introduction -->
This report analyzes daily temperature recordings across three major cities: 
Lagos, Abuja, and Ibadan. The objective is to use NumPy operations to determine
peak daily temperatures, compare temperature variations, and show the 
performance advantages of NumPy over Python lists.

In [42]:
# Import Numpy
import numpy as np

# Dataset
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

# Convert Data to NumPy Arrays
lagos_array = np.array(lagos)
abuja_array = np.array(abuja)
ibadan_array = np.array(ibadan)

In [46]:
# Array Inspection
print("Lagos Array:", "| Data Type:", lagos_array.dtype)
print("Abuja Array:", "| Data Type:", abuja_array.dtype)
print("Ibadan Array:",  "| Data Type:", ibadan_array.dtype)

Lagos Array: | Data Type: float64
Abuja Array: | Data Type: float64
Ibadan Array: | Data Type: float64


In [47]:
# Numerical Operations
max_temperature = np.maximum(np.maximum(lagos_array, abuja_array), ibadan_array)
highest_per_day = np.where(max_temperature == lagos_array, 'Lagos', 
                  np.where(max_temperature == abuja_array, 'Abuja', 'Ibadan'))

print("Highest Location Per Day:", highest_per_day)

# Increase every recorded temperature by 1°C
increased_lagos = lagos_array + 1
increased_abuja = abuja_array + 1
increased_ibadan = ibadan_array + 1

print("Lagos (+1°C):", increased_lagos)
print("Abuja (+1°C):", increased_abuja)
print("Ibadan (+1°C):", increased_ibadan)

Highest Location Per Day: ['Lagos' 'Lagos' 'Lagos' 'Abuja' 'Abuja']
Lagos (+1°C): [28.5 30.  31.5 29.  32. ]
Abuja (+1°C): [26.  29.  30.5 31.  33. ]
Ibadan (+1°C): [27.5 29.5 30.  28.5 31.5]


In [48]:
# Lagos vs Abuja
temperature_difference = lagos_array - abuja_array

print("Temperature Difference (Lagos - Abuja):", temperature_difference)

Temperature Difference (Lagos - Abuja): [ 2.5  1.   1.  -2.  -1. ]


Findings

1. Lagos recorded the highest temperatures for the first three days. Following that, Abuja was the hottest location for the last three days <br>
2. Lagos recorded a significantly hotter temperature than abuja on the first day
3. Abuja showed the greatest overall temperature increase across the days


Conclusion <br>

Numpy makes multi-location analysis efficient with the element-wise math feature it incoporates.
    This can only be possible with python list by extra logic